plugins {
    id 'com.vanniktech.maven.publish' version '0.36.0' apply false
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'com.vanniktech.maven.publish'

    group = providers.gradleProperty('GROUP').get()
    version = providers.gradleProperty('VERSION_NAME').get()

    repositories {
        mavenCentral()
    }

    tasks.withType(JavaCompile).configureEach {
        options.release = 17
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()
    }

    mavenPublishing {
        publishToMavenCentral()
        signAllPublications()
    }
}
