import com.github.spotbugs.snom.Confidence
import com.github.spotbugs.snom.Effort

plugins {
    alias(libs.plugins.mavenPublish) apply false
    alias(libs.plugins.spotless) apply false
    alias(libs.plugins.spotbugs) apply false
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'jacoco'
    apply plugin: 'com.diffplug.spotless'
    apply plugin: 'com.github.spotbugs'
    apply plugin: 'com.vanniktech.maven.publish'

    group = providers.gradleProperty('GROUP').get()
    version = providers.gradleProperty('VERSION_NAME').get()

    repositories {
        mavenCentral()
    }

    tasks.withType(JavaCompile).configureEach {
        options.release = 17
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()

        ['DOCKER_HOST', 'DOCKER_API_VERSION', 'TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE', 'TESTCONTAINERS_RYUK_DISABLED'].each { var ->
            if (System.getenv(var)) { environment var, System.getenv(var) }
        }
        if (System.getenv('DOCKER_API_VERSION')) {
            systemProperty 'api.version', System.getenv('DOCKER_API_VERSION')
        }
        systemProperty 'http.nonProxyHosts', 'localhost|127.0.0.1|host.docker.internal'

        finalizedBy tasks.named('jacocoTestReport')
    }

    tasks.named('jacocoTestReport') {
        mustRunAfter tasks.named('test')
        reports {
            xml.required = true
            html.required = false
        }
    }

    mavenPublishing {
        publishToMavenCentral()
        signAllPublications()
    }

    spotless {
        java {
            googleJavaFormat()
        }
    }

    spotbugs {
        ignoreFailures.set(true)
        effort.set(Effort.DEFAULT)
        reportLevel.set(Confidence.valueOf('LOW'))
    }
}
