[versions]
testcontainers = "2.0.5"
junit = "6.1.3"
assertj = "3.27.7"
awsSdk = "2.54.2"
springBoot3 = "3.5.16"
springBoot4 = "3.5.16"
springCloudAws3 = "3.4.2"
springCloudAws4 = "3.4.2"

[libraries]
testcontainers-bom = { module = "org.testcontainers:testcontainers-bom", version.ref = "testcontainers" }
testcontainers = { module = "org.testcontainers:testcontainers" }
testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
aws-sdk-bom = { module = "software.amazon.awssdk:bom", version.ref = "awsSdk" }
aws-sdk-s3 = { module = "software.amazon.awssdk:s3" }
aws-sdk-iam = { module = "software.amazon.awssdk:iam" }
spring-boot3-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "springBoot3" }
spring-boot3-testcontainers = { module = "org.springframework.boot:spring-boot-testcontainers" }
spring-boot3-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot4-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "springBoot4" }
spring-boot4-testcontainers = { module = "org.springframework.boot:spring-boot-testcontainers" }
spring-boot4-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-cloud-aws3-dependencies = { module = "io.awspring.cloud:spring-cloud-aws-dependencies", version.ref = "springCloudAws3" }
spring-cloud-aws3-autoconfigure = { module = "io.awspring.cloud:spring-cloud-aws-autoconfigure" }
spring-cloud-aws3-starter-s3 = { module = "io.awspring.cloud:spring-cloud-aws-starter-s3" }
spring-cloud-aws4-dependencies = { module = "io.awspring.cloud:spring-cloud-aws-dependencies", version.ref = "springCloudAws4" }
spring-cloud-aws4-autoconfigure = { module = "io.awspring.cloud:spring-cloud-aws-autoconfigure" }
spring-cloud-aws4-starter-s3 = { module = "io.awspring.cloud:spring-cloud-aws-starter-s3" }

[plugins]
mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.37.0" }
