dependencies {
    api platform(libs.testcontainers.bom)
    api libs.testcontainers

    testImplementation libs.testcontainers.junit.jupiter
    testImplementation libs.junit.jupiter
    testImplementation libs.assertj.core
    testRuntimeOnly libs.junit.platform.launcher

    testImplementation platform(libs.aws.sdk.bom)
    testImplementation libs.aws.sdk.s3
    testImplementation libs.aws.sdk.iam
}
