dependencies {
    api platform("org.testcontainers:testcontainers-bom:${providers.gradleProperty('testcontainersVersion').get()}")
    api 'org.testcontainers:testcontainers'

    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation "org.junit.jupiter:junit-jupiter:${providers.gradleProperty('junitVersion').get()}"
    testImplementation "org.assertj:assertj-core:${providers.gradleProperty('assertjVersion').get()}"
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    testImplementation platform("software.amazon.awssdk:bom:${providers.gradleProperty('awsSdkVersion').get()}")
    testImplementation 'software.amazon.awssdk:s3'
    testImplementation 'software.amazon.awssdk:iam'
}

tasks.withType(Test).configureEach {
    ['DOCKER_HOST', 'DOCKER_API_VERSION', 'TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE'].each { var ->
        if (System.getenv(var)) { environment var, System.getenv(var) }
    }
    if (System.getenv('DOCKER_API_VERSION')) {
        systemProperty 'api.version', System.getenv('DOCKER_API_VERSION')
    }
    environment 'TESTCONTAINERS_RYUK_DISABLED', 'true'
    systemProperty 'http.nonProxyHosts', 'localhost|127.0.0.1|host.docker.internal'
}
