dependencies {
    api project(':testcontainers-moto')

    compileOnly platform(libs.spring.boot3.dependencies)
    compileOnly libs.spring.boot3.testcontainers
    compileOnly platform(libs.spring.cloud.aws3.dependencies)
    compileOnly libs.spring.cloud.aws3.autoconfigure
    compileOnly platform(libs.aws.sdk.bom)
    compileOnly libs.aws.sdk.s3

    testImplementation libs.junit.jupiter
    testImplementation libs.assertj.core
    testRuntimeOnly libs.junit.platform.launcher

    testImplementation platform(libs.spring.boot3.dependencies)
    testImplementation libs.spring.boot3.testcontainers
    testImplementation libs.spring.boot3.starter.test
    testImplementation libs.testcontainers.junit.jupiter

    testImplementation platform(libs.spring.cloud.aws3.dependencies)
    testImplementation libs.spring.cloud.aws3.starter.s3
    testImplementation platform(libs.aws.sdk.bom)
}

testing {
    suites {
        testBoot4(JvmTestSuite) {
            sources {
                java.srcDirs('src/test/java')
            }

            dependencies {
                implementation project()
                implementation platform(libs.spring.boot4.dependencies)
                implementation libs.spring.boot4.testcontainers
                implementation platform(libs.spring.cloud.aws4.dependencies)
                implementation libs.spring.cloud.aws4.autoconfigure
                implementation platform(libs.aws.sdk.bom)
                implementation libs.aws.sdk.s3
                implementation libs.junit.jupiter
                implementation libs.assertj.core
                implementation libs.junit.platform.launcher
                implementation libs.spring.boot4.starter.test
                implementation libs.testcontainers.junit.jupiter
                implementation libs.spring.cloud.aws4.starter.s3
            }

            targets.all {
                testTask.configure {
                    useJUnitPlatform()
                }
            }
        }
    }
}

tasks.named('check') {
    dependsOn testBoot4
}
